### PR TITLE
properly map test outputs to input notebook cells

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
The time per notebook is contained in the log file, which is a bit unhandy.

**Comment by cwehmeyer** [comment]
> The time per notebook is contained in the log file, which is a bit unhandy.

Indeed... I can only find the time per container and the listings of the slowest cells within each container.

**Comment by cwehmeyer** [comment]
@marscher: can we merge this?

**Comment by marscher** [comment]
On 12.07.2018 20:40, Christoph Wehmeyer wrote:
> @marscher: can we merge this?
> 

yes, but it is still not doing what i'm intending - store the output of
the execution... (it worked locally though)

**Pull request merged**
