### PR TITLE
Updated readme, setup

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by cwehmeyer** [comment]
Thanks!

One question, though: is versioneer a better choice than setuptools_scm (and setuptools_scm_git_archive)?

**Comment by marscher** [comment]
On 28.06.2018 15:50, Christoph Wehmeyer wrote:
> Thanks!
> 
> One question, though: is versioneer a better choice than setuptools_scm (and setuptools_scm_git_archive)?
> 

I prefer it, since I have only good experiences with it. The other tools
still contain too many bugs to be production reader IMHO. Of course
versioneer pollutes the repo a bit, but this is a small price to pay for
this valuable asset.

**Comment by cwehmeyer** [comment]
The error is related to a change in PyEMMA's `plot_feature_histograms` function and will be fixed upon merging my feature_plotting branch.

**Comment by marscher** [comment]
On 28.06.2018 16:40, Christoph Wehmeyer wrote:
> The error is related to a change in PyEMMA's `plot_feature_histograms` function and will be fixed upon merging my feature_plotting branch.
> 

ok, this change actually broke the api and btw the docstring of the
function is also wrong (in pyemma).

**Comment by cwehmeyer** [comment]
> ok, this change actually broke the api and btw the docstring of the function is also wrong (in pyemma).

This function is pretty new, so I do not worry too much about the API. But the incorrect docstring does bother me. Can we patch this somehow?

**Comment by marscher** [comment]
You mean in the release from like 3 hours ago?

**Comment by cwehmeyer** [comment]
Yes.

**Comment by marscher** [comment]
I can have a look. But I would suggest to wait to build a patched
version until we have accumulated something more serious, eg. one will
discover something which really justifies this workload.

**Comment by cwehmeyer** [comment]
Given that the broken plot is the only source of error, I'd say go ahead and merge. Thanks for taking care of this!

**Pull request merged**
