### PR TITLE
PDF available for download

### PR DESCRIPTION
**Pull request by thempel**
Includes a link to department FTP server 
#132

### CODE REVIEW

**Comment by marscher** [comment]
ftp is a good idea, Chris and I discussed, that we should attach the pdf version as release asset on Github. This way it is ensured, that the (tagged) version of the article is synchronized with the pdf (we could in principle do this automatically via CI, but it would require a bit of work).

**Comment by thempel** [comment]
Yes, we should do that in the long run. I would still merge this to have a temporary, easy-to-remove solution for the issue posted above.

**Comment by marscher** [comment]
https://github.com/markovmodel/pyemma_tutorials/releases/edit/v0.3 @thempel you can drag n drop the pdf file here. In addition we can have the ftp, if it is desirable.

**Comment by thempel** [comment]
Ok, done. I believe it's still good to have the link in the manuscript folder. Maybe, we can link it to the release asset file at some point (right now I don't see how this link will change once a new file is added to a new release).

**Pull request merged**
