### PR TITLE
[manuscript] [WIP] simplify HMM section, restructure citations

### PR DESCRIPTION
**Pull request by brookehus**
Starting this to build off Tim's work already done; not ready to merge.

### CODE REVIEW

**Comment by brookehus** [comment]
In the `hmm edits` commit, I removed the old/tutorial references from everything except the end of the section, and moved and extended Tim's addition to the discussion.

More coming for other things shortly.

**Comment by brookehus** [comment]
In the above commit, I flush out some details. I add a reference to the [MD tutorial](https://github.com/MobleyLab/basic_simulation_training/tree/master/paper) that was just accepted to livecoms, and have posted an [issue](https://github.com/MobleyLab/basic_simulation_training/issues/101) on their page asking for the best citation. For MEMMs, I reference a section in my JACS perspective; I thought this might be the best solution since there are a ton of citations and it's kind of out of the scope of what we cover.

Please feel free to change/give comments. If there's a part that still needs to be looked at, please direct me to it!

**Comment by marscher** [comment]
Is this exception caused by plot_1D_histogram_trajectories or is the the
brand new matplotlib (3.0.2) version? It says some lines are expected to
cross each other.

ValueError: Given lines do not intersect. Please verify that the angles
are not equal or differ by 180 degrees.

This is happening during rendering.

Lets see if it happens all of the time.

**Comment by brookehus** [comment]
Now that I've pulled from `master` it gives the same error you already reported. But interestingly, the top of the log file still says,

```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
```

**Comment by marscher** [comment]
https://github.com/conda/conda-build/issues/3170

**Comment by brookehus** [comment]
@marscher should we merge and deal w/ the other thing separately

**Comment by marscher** [comment]
what was that latest merge commit good for? 

We can treat the matplotlib issue separately.

**Pull request merged**
