### PR TITLE
Review Notebooks

### PR DESCRIPTION
**Pull request by thempel**
Great work! I've mainly some corrected typos and added some details in the PR. Some more general thoughts for discussion here: 

- In NB 1 we use `pyemma.plots.plot_free_energy()` and in the second `plt.scatter()` for basically the same thing. Shouldn't we consistently use the pyemma function? Not sure if we don't confuse people when having fake density plots mixed up with logarithmic histograms. Especially in NB2: Pentapeptide-section uses both.

- in NB 2: Do people know what a slow process is when it is mentioned for the first time? It's not really captured by histograms. I've added some trajectory into the histogram in the first plot, please feel free to delete / modify. It's a bit messy and difficult to read the code. Maybe it would be better to just plot them as done later.

- NB2: I'm not quite sure what the histogram of discrete trajectories teaches people... given that in most cases, one cannot reproduce those histograms, people might ask later why they don't see this with their own data in pyemma.

- nglview does not work for me at all.

- I haven't specifically looked at the code cells, but it runs. One could probably make it easier for beginners by putting some inline comments or removing fancy `*` operators... but probably we're addressing advanced python users only.

- I corrected for American English because it was mostly used for featuriZation and discretiZation...

### CODE REVIEW

**Comment by marscher** [comment]
please squash merge when review is finished!

**Comment by marscher** [comment]
@thempel Thank you very much for your feedback and instantly correcting stuff!

**Comment by thempel** [comment]
- NB4: eigenvector plots showed numerical instability in first (0th) eigenvector instead of a constant 1 as described; I've used `np.round()` and edge colors to circumvent the problem. Change if you don't like it. 
- NB4: should we add the sign structure to the eigenvector plots? I'm not sure if that would clutter the plots too much.
- Since I was confused by exactly this subtlety for a rather long time: Generally, I wouldn't call histogram blobs metastable states just from looking at them... They could be metastable, yes, but without any validation, we cannot rule out that they are connected by fast processes or, worse, are stable and disconnected. 
- system-overview NB: It runs without any error. I don't fully understand it's pedagogical purpose though. It not only contains the systems but also MSMs plus some analysis without explanation. I guess there's a hint somewhere else?
- system-overview NB: For di-ala (heavy atom positions), the third process is not resolved, but still we coarse grain into 4 states. It yields an interesting result for the scatter plot of the metastable assignments. Was that intended?

**Comment by cwehmeyer** [comment]
@thempel thanks a lot for your review and corrections!

**Pull request merged**
