### PR TITLE
Corrections

### PR DESCRIPTION
**Pull request by cwehmeyer**

### CODE REVIEW

**Comment by marscher** [comment]
I would suggest using xtc format for pentapeptide again to save resources (traffic). The dcd files are aligned, right?

**Comment by marscher** [comment]
LGTM

**Comment by cwehmeyer** [comment]
> I would suggest using xtc format for pentapeptide again to save resources (traffic). The dcd files are aligned, right?

The dcd files are, the xtc files are not. If we exchange everything that requires alignment, like the backbone atom positions in 00, we can switch back.

**Comment by thempel** [comment]
Do we need both, aligned and non-aligned?

**Pull request merged**
