### PR TITLE
Caveats nb

### PR DESCRIPTION
**Pull request by thempel**
The notebook contains 
- irreversibly connected dynamics and what it means for MSM estimation
- fully disconnected trajectories and how to identify them
- ill-conducted TICA analysis and what it yields

There is still some work to be done, please don't merge yet. I'm just opening the PR to get some feedback or new ideas. @cwehmeyer  What else did we want to include again?

### CODE REVIEW

**Comment by cwehmeyer** [comment]
Could you please share the `doublewell_oneway.npy` and `data/doublewell_disconnected.npy` datasets?

**Comment by marscher** [comment]
Thanks! The tests are not starting because the kernel name is unknown to the notebook testing plugin. Its name is "adaptivemd" while the plugin expects something like "Python3" or so - sorry for this technical detail.

@cwehmeyer Do you want to share the data for this notebook in mdshare as well?

**Comment by thempel** [comment]
Files are in the mdshare public folder, at least for now. It's not really data that can easily be generated in the notebooks because I'm talking about specific kinds of failures that occur stochastically. 

@marscher  Sorry, I'm updating this.

**Comment by cwehmeyer** [comment]
@thempel please remove the `repository='http://ftp.imp.fu-berlin.de/pub/cmb-data'`parameter again from `mdshare.fetch()` calls. The exceptions you have seen with urls containing `//` were actually  badly formatted and not the ones used internally to look up remote files.

**Comment by thempel** [comment]
Will do, but I'd like to have the notebook running in the meantime. What's the problem if not the string? Does it run for you without the `repository` argument? (Right now the server is down due to maintenance, I believe.)

**Comment by marscher** [comment]
On 06.06.2018 14:01, thempel wrote:
> Will do, but I'd like to have the notebook running in the meantime. What's the problem if not the string? Does it run for you without the `repository` argument? (Right now the server is down due to maintenance, I believe.)
> 

*sigh* we should have developed this offline feature of mdshare prior
the server move...

**Comment by cwehmeyer** [comment]
To follow up on the mdshare issue: the Jupyter kernel had not been restarted after the new files were deposited on the ftp server. Thus, the cached index was the cause of the problem.

**Comment by cwehmeyer** [comment]
@thempel: I'd recommend to rename the notebook into 07-common-problems (06 is @psolsson's notebook on observables) and we're all set.

**Pull request merged**
