### PR TITLE
consistent use of fragemented reader in nb 04

### LINKED ISSUE #22: Error in Visualize_metstable() step
I am getting the following error when i run this step 
my_samples = [pyemma.coordinates.save_traj(files, idist, outfile=None, top=pdb)
              for idist in msm.sample_by_distributions(coarse_msm.metastable_distributions, 50)]

visualize_metastable(my_samples, cmap)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-31-a71e1fb56cdf> in <module>()
      4 
      5 my_samples = [pyemma.coordinates.save_traj(files, idist, outfile=None, top=p)
----> 6               for idist in msm.sample_by_distributions(coarse_msm.metastable_distributions, 50)]
      7 
      8 visualize_metastable(my_samples, cmap, selection='backbone')

<ipython-input-31-a71e1fb56cdf> in <listcomp>(.0)
      4 
      5 my_samples = [pyemma.coordinates.save_traj(files, idist, outfile=None, top=p)
----> 6               for idist in msm.sample_by_distributions(coarse_msm.metastable_distributions, 50)]
      7 
      8 visualize_metastable(my_samples, cmap, selection='backbone')

~/miniconda3/lib/python3.5/site-packages/pyemma/coordinates/api.py in save_traj(traj_inp, indexes, outfile, top, stride, chunksize, image_molecules, verbose)
    741                          % (len(trajfiles), indexes[:,0].max()))
    742 
--> 743     traj = frames_from_files(trajfiles, top, indexes, chunksize, stride, reader=reader)
    744 
    745     # Avoid broken molecules

~/miniconda3/lib/python3.5/site-packages/pyemma/coordinates/data/util/frames_from_file.py in frames_from_files(files, top, frames, chunksize, stride, verbose, copy_not_join, reader)
    113                                 largest=largest_ind_in_traj,
    114                                 filename=reader.filenames[itraj],
--> 115                                 length=length))
    116 
    117     def set_reader_return_traj_objects(reader, flag):

ValueError: largest specified index (773234.0 * stride=773234.0 * 1=773234) is larger than trajectory length '/data4/SINGAM/CNT_PROTEIn/CNT_PROTEIN_IONS/CNT_PROTEIn/output/run_23_cnt.dcd' = 13001
'

Can you please help me in fixing the code. Even with the tutorial (pentapetide) I am getting similar error

### PR DESCRIPTION
**Pull request by cwehmeyer**
This fixes #22.

### CODE REVIEW

**Comment by marscher** [comment]
Good catch! Is it mentioned in the description of the cell that we need to wrap the files once more to lime them together? I think it is important to explicitly say so.

**Comment by cwehmeyer** [comment]
Not in NB04. The use of encapsulating `[]` is explained in NB01 for the pentapeptide system but not in the following notebooks.

**Comment by cwehmeyer** [comment]
I am a bit surprised that this did not show up in the automated testing before (fragmented reader usage was introduced in #18).

**Comment by marscher** [comment]
If the sampled indices were always smaller than the fragment length it would happily run.

**Pull request merged**
